export const dummyData = [
	{
		_id: "1",
		assetType: "Laptop",
		quantity: 50,
		reserved: 45,
	},
	{
		_id: "2",
		assetType: "Monitor",
		quantity: 75,
		reserved: 20,
	},
	{
		_id: "3",
		assetType: "Keyboard",
		quantity: 100,
		reserved: 25,
	},
	{
		_id: "4",
		assetType: "Mouse",
		quantity: 200,
		reserved: 100,
	},
	{
		_id: "5",
		assetType: "Printer",
		quantity: 30,
		reserved: 5,
	},
	{
		_id: "6",
		assetType: "Chair",
		quantity: 100,
		reserved: 15,
	},
	{
		_id: "7",
		assetType: "Desk",
		quantity: 40,
		reserved: 10,
	},
];

export const dummyAssets = [
	{
		_id: "1",
		assetType: "Laptop",
		assetCode: "1234",
		dateGiven: new Date(),
		userName: "John Doe",
	},
	{
		_id: "2",
		assetType: "Monitor",
		assetCode: "1235",
		dateGiven: new Date(),
		userName: "John Doe",
	},
	{
		_id: "3",
		assetType: "Keyboard",
		assetCode: "1236",
		dateGiven: new Date(),
		userName: "John Doe",
	},
	{
		_id: "4",
		assetType: "Mouse",
		assetCode: "1237",
		dateGiven: new Date(),
		userName: "John Doe",
	},
	{
		_id: "5",
		assetType: "Printer",
		assetCode: "1238",
		dateGiven: new Date(),
		userName: "John Doe",
	},
	{
		_id: "6",
		assetType: "Chair",
		assetCode: "1239",
		dateGiven: new Date(),
		userName: "John Doe",
	},
	{
		_id: "7",
		assetType: "Desk",
		assetCode: "1240",
		dateGiven: new Date(),
		userName: "John Doe",
	},
	{
		_id: "8",
		assetType: "Laptop",
		assetCode: "1241",
		dateGiven: new Date(),
		userName: "John Doe",
	},
	{
		_id: "9",
		assetType: "Monitor",
		assetCode: "1242",
		dateGiven: new Date(),
		userName: "John Doe",
	},
];
