import { EmployeeDataType } from "../pages/Employment/types/Employee";

const DummyEmployeeData: EmployeeDataType[] = [
	{
		id: 1,
		name: "John",
		surname: "Wick",
		username: "JohnWick",
		email: "johnwick@gmail.com",
		phone: "123456789",
		salary: 1000,
		teamLeader: "Iron Man",
		startDate: "01/07/2024",
		position: "Frontend Developer",
		status: "Working",
		contract: null,
	},
	{
		id: 2,
		name: "Jane",
		surname: "Doe",
		username: "JaneDoe",
		email: "janedoe@gmail.com",
		phone: "987654321",
		salary: 1200,
		teamLeader: "Iron Man",
		startDate: "15/07/2024",
		position: "Backend Developer",
		status: "Working",
		contract: null,
	},
	{
		id: 3,
		name: "Peter",
		surname: "Parker",
		username: "SpiderMan",
		email: "spiderman@gmail.com",
		phone: "456789123",
		salary: 1100,
		teamLeader: "Iron Man",
		startDate: "20/07/2024",
		position: "Full Stack Developer",
		status: "Remote",
		contract: null,
	},
	{
		id: 4,
		name: "Bruce",
		surname: "Wayne",
		username: "Batman",
		email: "batman@gmail.com",
		phone: "789123456",
		salary: 1300,
		teamLeader: "Iron Man",
		startDate: "25/07/2024",
		position: "DevOps Engineer",
		status: "Remote",
		contract: null,
	},
	{
		id: 5,
		name: "Clark",
		surname: "Kent",
		username: "Superman",
		email: "superman@gmail.com",
		phone: "321654987",
		salary: 1150,
		teamLeader: "Iron Man",
		startDate: "30/07/2024",
		position: "Frontend Developer",
		status: "Remote",
		contract: null,
	},
	{
		id: 6,
		name: "Diana",
		surname: "Prince",
		username: "WonderWoman",
		email: "wonderwoman@gmail.com",
		phone: "654987321",
		salary: 1250,
		teamLeader: "Iron Man",
		startDate: "05/08/2024",
		position: "Backend Developer",
		status: "Working",
		contract: null,
	},
	{
		id: 7,
		name: "Tony",
		surname: "Stark",
		username: "IronMan",
		email: "ironman@gmail.com",
		phone: "789654123",
		salary: 1400,
		teamLeader: "Captain America",
		startDate: "10/08/2024",
		position: "Full Stack Developer",
		status: "Working",
		contract: null,
	},
	{
		id: 8,
		name: "Steve",
		surname: "Rogers",
		username: "CaptainAmerica",
		email: "captainamerica@gmail.com",
		phone: "147258369",
		salary: 1350,
		teamLeader: "Captain America",
		startDate: "15/08/2024",
		position: "DevOps Engineer",
		status: "Working",
		contract: null,
	},
	{
		id: 9,
		name: "Natasha",
		surname: "Romanoff",
		username: "BlackWidow",
		email: "blackwidow@gmail.com",
		phone: "258369147",
		salary: 1280,
		teamLeader: "Captain America",
		startDate: "20/08/2024",
		position: "Frontend Developer",
		status: "On Leave",
		contract: null,
	},
	{
		id: 10,
		name: "Bruce",
		surname: "Banner",
		username: "Hulk",
		email: "hulk@gmail.com",
		phone: "369147258",
		salary: 1320,
		teamLeader: "Captain America",
		startDate: "25/08/2024",
		position: "Backend Developer",
		status: "Working",
		contract: null,
	},
	{
		id: 11,
		name: "Thor",
		surname: "Odinson",
		username: "Thor",
		email: "thor@gmail.com",
		phone: "753951456",
		salary: 1370,
		teamLeader: "Captain America",
		startDate: "30/08/2024",
		position: "Full Stack Developer",
		status: "Remote",
		contract: null,
	},
	{
		id: 12,
		name: "Wanda",
		surname: "Maximoff",
		username: "ScarletWitch",
		email: "scarletwitch@gmail.com",
		phone: "951753852",
		salary: 1180,
		teamLeader: "Captain America",
		startDate: "05/09/2024",
		position: "DevOps Engineer",
		status: "Working",
		contract: null,
	},
	{
		id: 13,
		name: "Stephen",
		surname: "Strange",
		username: "DoctorStrange",
		email: "doctorstrange@gmail.com",
		phone: "852951753",
		salary: 1210,
		teamLeader: "Captain America",
		startDate: "10/09/2024",
		position: "Frontend Developer",
		status: "Working",
		contract: null,
	},
	{
		id: 14,
		name: "Carol",
		surname: "Danvers",
		username: "CaptainMarvel",
		email: "captainmarvel@gmail.com",
		phone: "753852951",
		salary: 1240,
		teamLeader: "Captain America",
		startDate: "15/09/2024",
		position: "Backend Developer",
		status: "Working",
		contract: null,
	},
	{
		id: 15,
		name: "Scott",
		surname: "Lang",
		username: "AntMan",
		email: "antman@gmail.com",
		phone: "456123789",
		salary: 1190,
		teamLeader: "Captain America",
		startDate: "20/09/2024",
		position: "Full Stack Developer",
		status: "Working",
		contract: null,
	},
	{
		id: 16,
		name: "Sam",
		surname: "Wilson",
		username: "Falcon",
		email: "falcon@gmail.com",
		phone: "123789456",
		salary: 1250,
		teamLeader: "Captain America",
		startDate: "25/09/2024",
		position: "DevOps Engineer",
		status: "Working",
		contract: null,
	},
	{
		id: 17,
		name: "Bucky",
		surname: "Barnes",
		username: "WinterSoldier",
		email: "wintersoldier@gmail.com",
		phone: "789456123",
		salary: 1300,
		teamLeader: "Captain America",
		startDate: "30/09/2024",
		position: "Frontend Developer",
		status: "Working",
		contract: null,
	},
	{
		id: 18,
		name: "T'Challa",
		surname: "Udaku",
		username: "BlackPanther",
		email: "blackpanther@gmail.com",
		phone: "147369258",
		salary: 1350,
		teamLeader: "Captain America",
		startDate: "05/10/2024",
		position: "Backend Developer",
		status: "Remote",
		contract: null,
	},
	{
		id: 19,
		name: "Peter",
		surname: "Quill",
		username: "StarLord",
		email: "starlord@gmail.com",
		phone: "258147369",
		salary: 1380,
		teamLeader: "Captain America",
		startDate: "10/10/2024",
		position: "Full Stack Developer",
		status: "Working",
		contract: null,
	},
	{
		id: 20,
		name: "Gamora",
		surname: "Zen-Whoberi",
		username: "Gamora",
		email: "gamora@gmail.com",
		phone: "369258147",
		salary: 1320,
		teamLeader: "Captain America",
		startDate: "15/10/2024",
		position: "DevOps Engineer",
		status: "Working",
		contract: null,
	},
];

export default DummyEmployeeData;
