const DummyRecruitmentData = [
  {
    id: 1,
    name: "John Doe",
    email: "jd@gmail.com",
    position: "Frontend Developer",
    applicationPhase: "First Interview",
    dateSubmitted: "2021-09-01",
    reference: "Linkedin",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@gmail.com",
    position: "Backend Developer",
    applicationPhase: "First Interview",
    dateSubmitted: "2021-08-15",
    reference: "Referral",
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@gmail.com",
    position: "Fullstack Developer",
    applicationPhase: "Second Interview",
    dateSubmitted: "2021-07-23",
    reference: "Company Website",
  },
  {
    id: 4,
    name: "Bob Brown",
    email: "bob.brown@gmail.com",
    position: "Data Scientist",
    applicationPhase: "Final Interview",
    dateSubmitted: "2021-06-30",
    reference: "Job Board",
  },
  {
    id: 5,
    name: "Charlie Davis",
    email: "charlie.davis@gmail.com",
    position: "Frontend Developer",
    applicationPhase: "Offer Made",
    dateSubmitted: "2021-05-20",
    reference: "LinkedIn",
  },
  {
    id: 6,
    name: "Diana Evans",
    email: "diana.evans@gmail.com",
    position: "Backend Developer",
    applicationPhase: "Applied",
    dateSubmitted: "2021-04-10",
    reference: "Referral",
  },
  {
    id: 7,
    name: "Eve Foster",
    email: "eve.foster@gmail.com",
    position: "Fullstack Developer",
    applicationPhase: "First Interview",
    dateSubmitted: "2021-03-05",
    reference: "Company Website",
  },
  {
    id: 8,
    name: "Frank Green",
    email: "frank.green@gmail.com",
    position: "Data Scientist",
    applicationPhase: "Second Interview",
    dateSubmitted: "2021-02-17",
    reference: "Job Board",
  },
  {
    id: 9,
    name: "Grace Hill",
    email: "grace.hill@gmail.com",
    position: "Frontend Developer",
    applicationPhase: "Final Interview",
    dateSubmitted: "2021-01-12",
    reference: "LinkedIn",
  },
  {
    id: 10,
    name: "Henry Irwin",
    email: "henry.irwin@gmail.com",
    position: "Backend Developer",
    applicationPhase: "Offer Made",
    dateSubmitted: "2021-12-25",
    reference: "Referral",
  },
  {
    id: 11,
    name: "Ivy Jackson",
    email: "ivy.jackson@gmail.com",
    position: "Fullstack Developer",
    applicationPhase: "Applied",
    dateSubmitted: "2021-11-11",
    reference: "Company Website",
  },
  {
    id: 12,
    name: "Jack Kelly",
    email: "jack.kelly@gmail.com",
    position: "Data Scientist",
    applicationPhase: "First Interview",
    dateSubmitted: "2021-10-19",
    reference: "Job Board",
  },
  {
    id: 13,
    name: "Karen Lewis",
    email: "karen.lewis@gmail.com",
    position: "Frontend Developer",
    applicationPhase: "Second Interview",
    dateSubmitted: "2021-09-04",
    reference: "LinkedIn",
  },
  {
    id: 14,
    name: "Leo Martin",
    email: "leo.martin@gmail.com",
    position: "Backend Developer",
    applicationPhase: "Final Interview",
    dateSubmitted: "2021-08-21",
    reference: "Referral",
  },
  {
    id: 15,
    name: "Mia Nelson",
    email: "mia.nelson@gmail.com",
    position: "Fullstack Developer",
    applicationPhase: "Offer Made",
    dateSubmitted: "2021-07-29",
    reference: "Company Website",
  },
  {
    id: 16,
    name: "Nina Olson",
    email: "nina.olson@gmail.com",
    position: "Data Scientist",
    applicationPhase: "Applied",
    dateSubmitted: "2021-06-07",
    reference: "Job Board",
  },
  {
    id: 17,
    name: "Oscar Parker",
    email: "oscar.parker@gmail.com",
    position: "Frontend Developer",
    applicationPhase: "First Interview",
    dateSubmitted: "2021-05-16",
    reference: "LinkedIn",
  },
  {
    id: 18,
    name: "Paula Quinn",
    email: "paula.quinn@gmail.com",
    position: "Backend Developer",
    applicationPhase: "Second Interview",
    dateSubmitted: "2021-04-23",
    reference: "Referral",
  },
  {
    id: 19,
    name: "Quincy Roberts",
    email: "quincy.roberts@gmail.com",
    position: "Fullstack Developer",
    applicationPhase: "Final Interview",
    dateSubmitted: "2021-03-09",
    reference: "Company Website",
  },
  {
    id: 20,
    name: "Rachel Scott",
    email: "rachel.scott@gmail.com",
    position: "Data Scientist",
    applicationPhase: "Offer Made",
    dateSubmitted: "2021-02-26",
    reference: "Job Board",
  },
  {
    id: 21,
    name: "Sam Taylor",
    email: "sam.taylor@gmail.com",
    position: "Frontend Developer",
    applicationPhase: "Applied",
    dateSubmitted: "2021-01-18",
    reference: "LinkedIn",
  },
  {
    id: 22,
    name: "Tina Underwood",
    email: "tina.underwood@gmail.com",
    position: "Backend Developer",
    applicationPhase: "First Interview",
    dateSubmitted: "2021-12-03",
    reference: "Referral",
  },
  {
    id: 23,
    name: "Uma Villanueva",
    email: "uma.villanueva@gmail.com",
    position: "Fullstack Developer",
    applicationPhase: "Second Interview",
    dateSubmitted: "2021-11-27",
    reference: "Company Website",
  },
  {
    id: 24,
    name: "Victor White",
    email: "victor.white@gmail.com",
    position: "Data Scientist",
    applicationPhase: "Final Interview",
    dateSubmitted: "2021-10-10",
    reference: "Job Board",
  },
  {
    id: 25,
    name: "Wendy Xie",
    email: "wendy.xie@gmail.com",
    position: "Frontend Developer",
    applicationPhase: "Offer Made",
    dateSubmitted: "2021-09-14",
    reference: "LinkedIn",
  },
  {
    id: 26,
    name: "Xavier Young",
    email: "xavier.young@gmail.com",
    position: "Backend Developer",
    applicationPhase: "Applied",
    dateSubmitted: "2021-08-18",
    reference: "Referral",
  },
  {
    id: 27,
    name: "Yara Zimmer",
    email: "yara.zimmer@gmail.com",
    position: "Fullstack Developer",
    applicationPhase: "First Interview",
    dateSubmitted: "2021-07-05",
    reference: "Company Website",
  },
  {
    id: 28,
    name: "Zane Allen",
    email: "zane.allen@gmail.com",
    position: "Data Scientist",
    applicationPhase: "Second Interview",
    dateSubmitted: "2021-06-12",
    reference: "Job Board",
  },
  {
    id: 29,
    name: "Adam Baker",
    email: "adam.baker@gmail.com",
    position: "Frontend Developer",
    applicationPhase: "Final Interview",
    dateSubmitted: "2021-05-03",
    reference: "LinkedIn",
  },
  {
    id: 30,
    name: "Bella Carter",
    email: "bella.carter@gmail.com",
    position: "Backend Developer",
    applicationPhase: "Offer Made",
    dateSubmitted: "2021-04-28",
    reference: "Referral",
  },
  {
    id: 31,
    name: "Carl Diaz",
    email: "carl.diaz@gmail.com",
    position: "Fullstack Developer",
    applicationPhase: "Applied",
    dateSubmitted: "2021-03-11",
    reference: "Company Website",
  },
  {
    id: 32,
    name: "Dana Edwards",
    email: "dana.edwards@gmail.com",
    position: "Data Scientist",
    applicationPhase: "First Interview",
    dateSubmitted: "2021-02-21",
    reference: "Job Board",
  },
];

export default DummyRecruitmentData;
